### ISSUE TITLE
Meta: Formatting exceptions

### ISSUE THREAD

**Issue by domfarolino** [domfarolino/specfmt#9]
Specfmt currently tries to format a bunch of things that shouldn't actually be formatted at all. This is most obvious when you run `specfmt --full-spec` on a spec, but also when you run it on a spec whose current branch diff simply contains things that shouldn't be formatted.

The purpose of this bug is to track the many things that should always be exempt from formatting:
 - [x] `<pre>` blocks
 - [x] `<xmp>` blocks ([bikeshed documentation](https://tabatkins.github.io/bikeshed/#xmp))
 - [x] `<style>` blocks
 - [x] `<script>` blocks
 - [x] `<svg>` blocks
 - [x] `<table>`s
 - [x] HTML comments (not sure what to do here, due to https://github.com/domfarolino/specfmt/blob/master/testcases/comment.in.html)
 - [x] All of the definitions inside the https://html.spec.whatwg.org/C#dependencies section (see https://github.com/domfarolino/specfmt/commit/8a5ad5ad37cfb045b7658bc7b5ab50a9bad40724)
 - [x] Markdown lists, e.g., some start with numbers `N. Foo` but others start with `:` and `::` (see [example here](https://github.com/WICG/nav-speculation/blob/main/prerendering.bs#L332-L336)) (see https://github.com/domfarolino/specfmt/pull/25)

Please contribute more items to the list!

----

In order to fix the exceptions above, we should probably have some general exception mechanism that does a single pass over all collected `Line`s of the spec and marks ones inside blocks in the above list as ineligible for formatting. This would behave like a very simple naive parser.

**Comment by mreichhoff** [comment]
one other item I noticed: I think markdown ordered lists can be wrapped incorrectly (e.g., [this line](https://github.com/privacycg/requestStorageAccessForOrigin/blob/5996517db98f973a16d1c9c64448c7b67d3d44dd/requestStorageAccessForOrigin.bs#L85) is switched to a single line: `1. Let |p| be [=a new promise=]. 1. If |doc| is not [=Document/fully active=], then [=reject=] |p|`). 

Given their sensitivity to wrapping and indentation, they might also belong on the list?

**Comment by domfarolino** [comment]
Ah yes I've noticed this too but failed to add to the list. Thanks, I've added it.

**Comment by domfarolino** [comment]
@mreichhoff For what it's worth the bug you pointed out is fixed by the tool now in version of `0.2.8`. The tool now works much better on bikeshed specs with markdown now.
